server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api

spring:
  application:
    name: booking-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      backend_booking:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      backend_booking:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 5s
  ratelimiter:
    instances:
      backend_booking:
        registerHealthIndicator: true
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
